sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 050120877633

  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucket-name: phosphophyllite
  redis:
    database: 0
    password:
    host: localhost
    port: 6379
  wechat:
    appid: wxd75e53bf679d3a01
    secret: 31e6da48b74c0a6908a675b820efcd41
    mchid: 1561414331
    notify-url: https://73c83068.r8.cpolar.top/notify/paySuccess
    refund-notify-url: https://73c83068.r8.cpolar.top/notify/refundSuccess