server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    password: ${sky.redis.password}
    database: ${sky.redis.database}
  servlet:
    multipart:
      max-file-size: 20MB #设置springBoot上传到服务器的单个文件的最大大小
      max-request-size: 40MB #设置springBoot上传到服务器的请求的总大小

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 管理端
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: admin
    # 设置jwt过期时间
    admin-ttl: 14400000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 用户端
    user-secret-key: user
    user-token-name: token
    user-ttl: 14400000
  alioss:
    endpoint: ${sky.alioss.endpoint}

    bucket-name: ${sky.alioss.bucket-name}}
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}














